site_name: 中国通用人工智能协会
repo_url: https://github.com/Hailaylin/agi-society-cn
copyright: Copyright &copy; 2016 - 2024 中国通用人工智能协会 粤ICP备2021145979号-1
theme:
  name: material
  custom_dir: overrides
  language: zh
  palette:
        # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换为夜间模式
      primary: indigo
      accent: orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换为日间模式
      accent: cyan

  font:
    text: Noto Sans SC
    code: Roboto Mono

  features:
    - header.autohide
    - navigation.tracking
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - navigation.top
    - navigation.instant

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.blocks.admonition:
      types:
      - new
      - settings
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - failure
      - danger
      - bug
      - example
      - quote
  - pymdownx.blocks.details:
  - pymdownx.blocks.definition:
  - pymdownx.blocks.tab:
      alternate_style: True

# 导航目录
nav:
  - NARS教程:
    - nars/nars_index.md
    # - nars/learning_resources.md

    - NARS理论:
      - nars/theory/aikr.md

    - NARS工程:

      - NARS各版实现:
        - nars/impl/introduction.md
        - nars/impl/index.md

        - nars/impl/20nar1.md
        - nars/impl/narjure.md
        - nars/impl/nars_cxin_py_to_ts.md
        - nars/impl/nars_python.md
        - nars/impl/nars_swift.md
        - nars/impl/narst.md
        - nars/impl/ona.md
        - nars/impl/openjunars.md
        - nars/impl/opennars.md
        - nars/impl/pynars.md

      - NARS衍生项目:
        - nars/derivative_project/introduction.md
        - nars/derivative_project/index.md


  - AGI 通用人工智能:
    - agi/agi_intro.md

  - SAI 专用人工智能:
    - sai/sai_intro.md
    - sai/llms.md

  - 思想书库:
    - other/other_intro.md
    - other/meaning_network.md
    - other/lazero.md
    - other/bingfengdecao.md
    - other/identity_of_intelligence.md
    - other/documents_and_qq_group.md

  - 历届会议:
    - 年会:
      - conference/conference_intro.md
      - conference/2024.md
      - conference/2023.md
    - 组会:
      - conference/group_meeting_catalogue.md

  - 关于我们:
    - about/about_us.md
    - about/web_arch.md
    - about/edit.md
    - about/team.md

